In [1]:
import numpy as np
from pandas import Series, DataFrame
import pandas as pd

In [2]:
dframe = DataFrame(np.arange(12).reshape(4,3))
# dframe is constructed by casting a 4-row by 3-col numpy array as a pandas DataFrame, pre-filled with values 0-11.
# Here the index defaults to [0,1,2,3], the columns to [0,1,2]

In [3]:
dframe

   0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [5]:
# Constructing a DataFrame from a Dictionary:
data = {'City':['SF','LA','NYC'],'Population':[837000,3880000,8400000]}
city_frame = DataFrame(data) 
# Creates a DataFrame with columns labeled City and Population, indexes of [0,1,2]
city_frame

  City  Population
0   SF      837000
1   LA     3880000
2  NYC     8400000

In [6]:
# Adding a Series to an existing DataFrame:
colors = Series(["Blue","Red"],index=[4,1])
dframe['Color']=colors
# dframe now has a Color column with Blue matched to index 4, Red to 1, and NaN after everything else.
colors

4    Blue
1     Red
dtype: object

In [15]:
#Now we'll learn DataFrames

#Let's get some data to play with. How about the NFL?
import webbrowser
website = 'https://en.wikipedia.org/wiki/NFL_win%E2%80%93loss_records'
webbrowser.open(website)

True

In [30]:
#Copy and read to get data
nfl_frame = pd.read_clipboard()

In [31]:
#Show
nfl_frame

,Rank,Team,Won,Lost,Tied,Pct.,First,NFL,Season,Total,Games,Division
0,1,Dallas,Cowboys,493,367,6,0.573,1960.000,866,NFC,East,NaN
1,2,Green,Bay,Packers,730,553,37.000,0.567,1921,"1,320",NFC,North
2,3,Chicago,Bears,744,568,42,0.565,1920.000,"1,354",NFC,North,NaN
3,4,Miami,Dolphins,439,341,4,0.563,1966.000,784,AFC,East,NaN
4,5,New,England,Patriots,476,383,9.000,0.554,1960,868,AFC,East
5,6,New,York,Giants,684,572,33.000,0.543,1925,"1,289",NFC,East
6,7,Denver,Broncos,465,393,10,0.541,1960.000,868,AFC,West,NaN
7,8,Minnesota,Vikings,457,387,10,0.541,1961.000,854,NFC,North,NaN
8,9,Baltimore,Ravens,181,154,1,0.540,1996.000,336,AFC,North,NaN
9,10,San,Francisco,49ers,522,450,14.000,0.537,1950,986,NFC,West
10,11,Indianapolis,Colts,502,441,7,0.532,1953.000,950,AFC,South,NaN
11,12,Oakland,Raiders,456,401,11,0.532,1960.000,868,AFC,West,NaN
12,13,Pittsburgh,Steelers,601,535,20,0.529,1933.000,"1,156",AFC,North,NaN
13,14,Kansas,City,Chiefs,447,409,12.000,0.522,1960,868,AFC,West
14,15,Washington,Redskins,586,572,28,0.506,1932.000,"1,186",NFC,East,NaN
15,16,Seattle,Seahawks,325,318,1,0.505,1976.000,644,NFC,West,NaN
16,17,Cleveland,Browns,462,466,10,0.498,1950.000,938,AFC,North,NaN
17,18,Los,Angeles,Chargers,426,431,11.000,0.497,1960,868,AFC,West
18,19,Los,Angeles,Rams,544,554,21.000,0.496,1937,"1,119",NFC,West
19,20,Carolina,Panthers,172,179,1,0.490,1995.000,352,NFC,South,NaN
20,21,Philadelphia,Eagles,555,591,26,0.485,1933.000,"1,172",NFC,East,NaN
21,22,Tennessee,Titans,413,449,6,0.479,1960.000,868,AFC,South,NaN
22,23,Buffalo,Bills,400,460,8,0.465,1960.000,868,AFC,East,NaN
23,24,Detroit,Lions,544,641,32,0.460,1930.000,"1,217",NFC,North,NaN
24,25,Cincinnati,Bengals,344,408,4,0.458,1968.000,756,AFC,North,NaN
25,26,New,York,Jets,392,468,8.000,0.456,1960,868,AFC,East
26,27,New,Orleans,Saints,338,427,5.000,0.442,1967,770,NFC,South
27,28,Houston,Texans,106,134,0,0.442,2002.000,240,AFC,South,NaN
28,29,Jacksonville,Jaguars,155,197,0,0.440,1995.000,352,AFC,South,NaN
29,30,Atlanta,Falcons,341,437,6,0.439,1966.000,784,NFC,South,NaN
30,31,Arizona,Cardinals,542,732,40,0.428,1920.000,"1,314",NFC,West,NaN
31,32,Tampa,Bay,Buccaneers,250,393,1.000,0.389,1976,644,NFC,South

In [32]:
# We can grab the oclumn names with .columns
nfl_frame.columns

Index(['Rank', 'Team', 'Won', 'Lost', 'Tied', 'Pct.', 'First', 'NFL', 'Season',
       'Total', 'Games', 'Division'],
      dtype='object')

In [33]:
#Lets see some specific data columns
DataFrame(nfl_frame,columns=['Team','First Season','Total Games'])

            Team  First Season  Total Games
0         Dallas           NaN          NaN
1          Green           NaN          NaN
2        Chicago           NaN          NaN
3          Miami           NaN          NaN
4            New           NaN          NaN
5            New           NaN          NaN
6         Denver           NaN          NaN
7      Minnesota           NaN          NaN
8      Baltimore           NaN          NaN
9            San           NaN          NaN
10  Indianapolis           NaN          NaN
11       Oakland           NaN          NaN
12    Pittsburgh           NaN          NaN
13        Kansas           NaN          NaN
14    Washington           NaN          NaN
15       Seattle           NaN          NaN
16     Cleveland           NaN          NaN
17           Los           NaN          NaN
18           Los           NaN          NaN
19      Carolina           NaN          NaN
20  Philadelphia           NaN          NaN
21     Tennessee           NaN          NaN
22       Buffalo           NaN          NaN
23       Detroit           NaN          NaN
24    Cincinnati           NaN          NaN
25           New           NaN          NaN
26           New           NaN          NaN
27       Houston           NaN          NaN
28  Jacksonville           NaN          NaN
29       Atlanta           NaN          NaN
30       Arizona           NaN          NaN
31         Tampa           NaN          NaN

In [34]:
#What happens if we ask for a column that doesn't exist?
DataFrame(nfl_frame,columns=['Team','First Season','Total Games','Stadium'])

            Team  First Season  Total Games  Stadium
0         Dallas           NaN          NaN      NaN
1          Green           NaN          NaN      NaN
2        Chicago           NaN          NaN      NaN
3          Miami           NaN          NaN      NaN
4            New           NaN          NaN      NaN
5            New           NaN          NaN      NaN
6         Denver           NaN          NaN      NaN
7      Minnesota           NaN          NaN      NaN
8      Baltimore           NaN          NaN      NaN
9            San           NaN          NaN      NaN
10  Indianapolis           NaN          NaN      NaN
11       Oakland           NaN          NaN      NaN
12    Pittsburgh           NaN          NaN      NaN
13        Kansas           NaN          NaN      NaN
14    Washington           NaN          NaN      NaN
15       Seattle           NaN          NaN      NaN
16     Cleveland           NaN          NaN      NaN
17           Los           NaN          NaN      NaN
18           Los           NaN          NaN      NaN
19      Carolina           NaN          NaN      NaN
20  Philadelphia           NaN          NaN      NaN
21     Tennessee           NaN          NaN      NaN
22       Buffalo           NaN          NaN      NaN
23       Detroit           NaN          NaN      NaN
24    Cincinnati           NaN          NaN      NaN
25           New           NaN          NaN      NaN
26           New           NaN          NaN      NaN
27       Houston           NaN          NaN      NaN
28  Jacksonville           NaN          NaN      NaN
29       Atlanta           NaN          NaN      NaN
30       Arizona           NaN          NaN      NaN
31         Tampa           NaN          NaN      NaN

In [21]:
# Call columns
nfl_frame.columns

Index(['Rank', 'Team', 'Won', 'Lost', 'Tied', 'Pct.', 'First', 'NFL', 'Season',
       'Total', 'Games', 'Division'],
      dtype='object')

In [22]:
#We can retrieve individual columns
nfl_frame.Team

0           Dallas
1            Green
2          Chicago
3            Miami
4              New
5              New
6           Denver
7        Minnesota
8        Baltimore
9              San
10    Indianapolis
11         Oakland
12      Pittsburgh
13          Kansas
14      Washington
15         Seattle
16       Cleveland
17             Los
18             Los
19        Carolina
20    Philadelphia
21       Tennessee
22         Buffalo
23         Detroit
24      Cincinnati
25             New
26             New
27         Houston
28    Jacksonville
29         Atlanta
30         Arizona
31           Tampa
Name: Team, dtype: object

In [23]:
#We can retrieve rows through indexing
nfl_frame.ix[3]

Rank               4
Team           Miami
Won         Dolphins
Lost             439
Tied             341
Pct.               4
First          0.563
NFL             1966
Season           784
Total            AFC
Games           East
Division         NaN
Name: 3, dtype: object

In [24]:
#We can also assign value sto entire columns
nfl_frame['Stadium']="Levi's Stadium" #Careful with the ' here

In [25]:
nfl_frame

,Rank,Team,Won,Lost,Tied,Pct.,First,NFL,Season,Total,Games,Division,Stadium
0,1,Dallas,Cowboys,493,367,6,0.573,1960.000,866,NFC,East,NaN,Levi's Stadium
1,2,Green,Bay,Packers,730,553,37.000,0.567,1921,"1,320",NFC,North,Levi's Stadium
2,3,Chicago,Bears,744,568,42,0.565,1920.000,"1,354",NFC,North,NaN,Levi's Stadium
3,4,Miami,Dolphins,439,341,4,0.563,1966.000,784,AFC,East,NaN,Levi's Stadium
4,5,New,England,Patriots,476,383,9.000,0.554,1960,868,AFC,East,Levi's Stadium
5,6,New,York,Giants,684,572,33.000,0.543,1925,"1,289",NFC,East,Levi's Stadium
6,7,Denver,Broncos,465,393,10,0.541,1960.000,868,AFC,West,NaN,Levi's Stadium
7,8,Minnesota,Vikings,457,387,10,0.541,1961.000,854,NFC,North,NaN,Levi's Stadium
8,9,Baltimore,Ravens,181,154,1,0.540,1996.000,336,AFC,North,NaN,Levi's Stadium
9,10,San,Francisco,49ers,522,450,14.000,0.537,1950,986,NFC,West,Levi's Stadium
10,11,Indianapolis,Colts,502,441,7,0.532,1953.000,950,AFC,South,NaN,Levi's Stadium
11,12,Oakland,Raiders,456,401,11,0.532,1960.000,868,AFC,West,NaN,Levi's Stadium
12,13,Pittsburgh,Steelers,601,535,20,0.529,1933.000,"1,156",AFC,North,NaN,Levi's Stadium
13,14,Kansas,City,Chiefs,447,409,12.000,0.522,1960,868,AFC,West,Levi's Stadium
14,15,Washington,Redskins,586,572,28,0.506,1932.000,"1,186",NFC,East,NaN,Levi's Stadium
15,16,Seattle,Seahawks,325,318,1,0.505,1976.000,644,NFC,West,NaN,Levi's Stadium
16,17,Cleveland,Browns,462,466,10,0.498,1950.000,938,AFC,North,NaN,Levi's Stadium
17,18,Los,Angeles,Chargers,426,431,11.000,0.497,1960,868,AFC,West,Levi's Stadium
18,19,Los,Angeles,Rams,544,554,21.000,0.496,1937,"1,119",NFC,West,Levi's Stadium
19,20,Carolina,Panthers,172,179,1,0.490,1995.000,352,NFC,South,NaN,Levi's Stadium
20,21,Philadelphia,Eagles,555,591,26,0.485,1933.000,"1,172",NFC,East,NaN,Levi's Stadium
21,22,Tennessee,Titans,413,449,6,0.479,1960.000,868,AFC,South,NaN,Levi's Stadium
22,23,Buffalo,Bills,400,460,8,0.465,1960.000,868,AFC,East,NaN,Levi's Stadium
23,24,Detroit,Lions,544,641,32,0.460,1930.000,"1,217",NFC,North,NaN,Levi's Stadium
24,25,Cincinnati,Bengals,344,408,4,0.458,1968.000,756,AFC,North,NaN,Levi's Stadium
25,26,New,York,Jets,392,468,8.000,0.456,1960,868,AFC,East,Levi's Stadium
26,27,New,Orleans,Saints,338,427,5.000,0.442,1967,770,NFC,South,Levi's Stadium
27,28,Houston,Texans,106,134,0,0.442,2002.000,240,AFC,South,NaN,Levi's Stadium
28,29,Jacksonville,Jaguars,155,197,0,0.440,1995.000,352,AFC,South,NaN,Levi's Stadium
29,30,Atlanta,Falcons,341,437,6,0.439,1966.000,784,NFC,South,NaN,Levi's Stadium
30,31,Arizona,Cardinals,542,732,40,0.428,1920.000,"1,314",NFC,West,NaN,Levi's Stadium
31,32,Tampa,Bay,Buccaneers,250,393,1.000,0.389,1976,644,NFC,South,Levi's Stadium

In [26]:
# Call columns
nfl_frame.columns

Index(['Rank', 'Team', 'Won', 'Lost', 'Tied', 'Pct.', 'First', 'NFL', 'Season',
       'Total', 'Games', 'Division', 'Stadium'],
      dtype='object')

In [27]:
#Adding a Series to a DataFrame
stadiums = Series(["Levi's Stadium","AT&T Stadium"],index=[4,0])

In [28]:
#Now input into the nfl DataFrame
nfl_frame['Stadium']=stadiums

#Show
nfl_frame

,Rank,Team,Won,Lost,Tied,Pct.,First,NFL,Season,Total,Games,Division,Stadium
0,1,Dallas,Cowboys,493,367,6,0.573,1960.000,866,NFC,East,NaN,AT&T Stadium
1,2,Green,Bay,Packers,730,553,37.000,0.567,1921,"1,320",NFC,North,NaN
2,3,Chicago,Bears,744,568,42,0.565,1920.000,"1,354",NFC,North,NaN,NaN
3,4,Miami,Dolphins,439,341,4,0.563,1966.000,784,AFC,East,NaN,NaN
4,5,New,England,Patriots,476,383,9.000,0.554,1960,868,AFC,East,Levi's Stadium
5,6,New,York,Giants,684,572,33.000,0.543,1925,"1,289",NFC,East,NaN
6,7,Denver,Broncos,465,393,10,0.541,1960.000,868,AFC,West,NaN,NaN
7,8,Minnesota,Vikings,457,387,10,0.541,1961.000,854,NFC,North,NaN,NaN
8,9,Baltimore,Ravens,181,154,1,0.540,1996.000,336,AFC,North,NaN,NaN
9,10,San,Francisco,49ers,522,450,14.000,0.537,1950,986,NFC,West,NaN
10,11,Indianapolis,Colts,502,441,7,0.532,1953.000,950,AFC,South,NaN,NaN
11,12,Oakland,Raiders,456,401,11,0.532,1960.000,868,AFC,West,NaN,NaN
12,13,Pittsburgh,Steelers,601,535,20,0.529,1933.000,"1,156",AFC,North,NaN,NaN
13,14,Kansas,City,Chiefs,447,409,12.000,0.522,1960,868,AFC,West,NaN
14,15,Washington,Redskins,586,572,28,0.506,1932.000,"1,186",NFC,East,NaN,NaN
15,16,Seattle,Seahawks,325,318,1,0.505,1976.000,644,NFC,West,NaN,NaN
16,17,Cleveland,Browns,462,466,10,0.498,1950.000,938,AFC,North,NaN,NaN
17,18,Los,Angeles,Chargers,426,431,11.000,0.497,1960,868,AFC,West,NaN
18,19,Los,Angeles,Rams,544,554,21.000,0.496,1937,"1,119",NFC,West,NaN
19,20,Carolina,Panthers,172,179,1,0.490,1995.000,352,NFC,South,NaN,NaN
20,21,Philadelphia,Eagles,555,591,26,0.485,1933.000,"1,172",NFC,East,NaN,NaN
21,22,Tennessee,Titans,413,449,6,0.479,1960.000,868,AFC,South,NaN,NaN
22,23,Buffalo,Bills,400,460,8,0.465,1960.000,868,AFC,East,NaN,NaN
23,24,Detroit,Lions,544,641,32,0.460,1930.000,"1,217",NFC,North,NaN,NaN
24,25,Cincinnati,Bengals,344,408,4,0.458,1968.000,756,AFC,North,NaN,NaN
25,26,New,York,Jets,392,468,8.000,0.456,1960,868,AFC,East,NaN
26,27,New,Orleans,Saints,338,427,5.000,0.442,1967,770,NFC,South,NaN
27,28,Houston,Texans,106,134,0,0.442,2002.000,240,AFC,South,NaN,NaN
28,29,Jacksonville,Jaguars,155,197,0,0.440,1995.000,352,AFC,South,NaN,NaN
29,30,Atlanta,Falcons,341,437,6,0.439,1966.000,784,NFC,South,NaN,NaN
30,31,Arizona,Cardinals,542,732,40,0.428,1920.000,"1,314",NFC,West,NaN,NaN
31,32,Tampa,Bay,Buccaneers,250,393,1.000,0.389,1976,644,NFC,South,NaN

In [ ]:
#We can also delete columns
del nfl_frame['Stadium']

nfl_frame

In [ ]:
#DataFrames can be constructed many ways. Another way is from a dictionary of equal length lists
data = {'City':['SF','LA','NYC'],
        'Population':[837000,3880000,8400000]}

city_frame = DataFrame(data)

#Show
city_frame